name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Login au registry privé
      - name: Log in to private Docker registry
        run: |
          echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY }} -u ${{ secrets.DOCKER_REGISTRY_USER }} --password-stdin

      # # 2️⃣ Login au registre Docker
      # - name: Log in to private Docker registry
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_REGISTRY_USER }}
      #     password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      #     registry: ${{ secrets.REGISTRY }}

      # 3️⃣ Build l'image Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY }}/portfolio:latest .

      # 4️⃣ Push l'image vers le registre
      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY }}/portfolio:latest

      # 5️⃣ Trigger Coolify deployment
      - name: Trigger Coolify Auto Deploy
        run: |
          curl -X POST "${{ secrets.COOLIFY_URL }}/api/deployments" \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "appId": "k0gcckks8ggooso4kkcgo0o0",
                "image": "${{ secrets.REGISTRY }}/portfolio:latest"
              }'